# Generated by Django 5.2.7 on 2025-10-20 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link_url', models.URLField(blank=True)),
                ('height_px', models.PositiveIntegerField(default=480)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('LP', 'LP'), ('UP', 'UP'), ('HS', 'HS')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programmes/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('min_team_size', models.PositiveIntegerField(default=2)),
                ('max_team_size', models.PositiveIntegerField(default=8)),
                ('apply_limit', models.PositiveSmallIntegerField(default=1)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RegisterCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('current', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('program_name', models.CharField(choices=[('LKG Music', 'LKG Music'), ('LKG Dance', 'LKG Dance'), ('LKG Drawing', 'LKG Drawing'), ('LKG Group Dance', 'LKG Group Dance'), ('UKG Music', 'UKG Music'), ('UKG Dance', 'UKG Dance'), ('UKG Drawing', 'UKG Drawing'), ('UKG Group Dance', 'UKG Group Dance'), ('LP Music', 'LP Music'), ('LP Dance', 'LP Dance'), ('LP Drawing', 'LP Drawing'), ('LP Group Dance', 'LP Group Dance'), ('UP Music', 'UP Music'), ('UP Dance', 'UP Dance'), ('UP Drawing', 'UP Drawing'), ('UP Group Dance', 'UP Group Dance'), ('HS Music', 'HS Music'), ('HS Dance', 'HS Dance'), ('HS Drawing', 'HS Drawing'), ('HS Group Dance', 'HS Group Dance')], max_length=40)),
                ('team_size', models.PositiveIntegerField(default=2)),
                ('register_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='eventapp.school')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
