# Generated by Django 5.2.7 on 2025-10-20 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={},
        ),
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventapp.school'),
        ),
    ]
