# Generated by Django 5.2.7 on 2025-10-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_alter_programme_options_alter_application_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='apply_limit',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='max_team_size',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='min_team_size',
        ),
        migrations.AlterField(
            model_name='programme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programme_images/'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='programme',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
