# Generated by Django 5.2.7 on 2025-10-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_remove_programme_apply_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='max_team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='programme',
            name='min_team_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
