# Generated by Django 5.2.7 on 2025-10-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_programme_max_team_size_programme_min_team_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='description',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='image',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='max_team_size',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='min_team_size',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='order',
        ),
        migrations.AddField(
            model_name='programme',
            name='apply_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
