# Generated by Django 5.2.7 on 2025-10-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_remove_programme_description_remove_programme_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
