# Generated by Django 5.2.7 on 2025-10-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_programme_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='apply_limit',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='programme',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programme_images/'),
        ),
        migrations.AddField(
            model_name='programme',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programme',
            name='category',
            field=models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('LP', 'LP'), ('UP', 'UP'), ('HS', 'HS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
