# Generated by Django 5.2.7 on 2025-10-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_remove_programme_apply_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='programme',
            name='apply_limit',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AddField(
            model_name='programme',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='team_max',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='programme',
            name='team_min',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
