# Generated by Django 5.2.7 on 2025-10-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_alter_programme_options_programme_apply_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='apply_limit',
        ),
        migrations.AlterField(
            model_name='programme',
            name='team_max',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='programme',
            name='team_min',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
