# Generated by Django 5.2.7 on 2025-10-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0009_remove_programme_apply_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='winner_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='winner_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
