# Generated by Django 5.0.1 on 2025-10-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_application_is_winner_application_winner_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='program_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='programme',
            name='category',
            field=models.CharField(choices=[('KG', 'KG'), ('LP', 'LP'), ('UP', 'UP'), ('HS', 'HS')], max_length=10),
        ),
    ]
